#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchemaGenerator
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[System.Data.Linq.Mapping.DatabaseAttribute(Name="AdventureWorks")]
	public partial class SchemaDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public SchemaDataContext() : 
				base(global::SchemaGenerator.Properties.Settings.Default.AdventureWorksConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public SchemaDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SchemaDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SchemaDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SchemaDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<COLUMN> COLUMNs
		{
			get
			{
				return this.GetTable<COLUMN>();
			}
		}
		
		public System.Data.Linq.Table<CONSTRAINT_COLUMN_USAGE> CONSTRAINT_COLUMN_USAGEs
		{
			get
			{
				return this.GetTable<CONSTRAINT_COLUMN_USAGE>();
			}
		}
		
		public System.Data.Linq.Table<REFERENTIAL_CONSTRAINT> REFERENTIAL_CONSTRAINTs
		{
			get
			{
				return this.GetTable<REFERENTIAL_CONSTRAINT>();
			}
		}
		
		public System.Data.Linq.Table<VIEW> VIEWs
		{
			get
			{
				return this.GetTable<VIEW>();
			}
		}
		
		public System.Data.Linq.Table<TABLE> TABLEs
		{
			get
			{
				return this.GetTable<TABLE>();
			}
		}
	}
	
	[Table(Name="INFORMATION_SCHEMA.COLUMNS")]
	public partial class COLUMN
	{
		
		private string _TABLE_CATALOG;
		
		private string _TABLE_SCHEMA;
		
		private string _TABLE_NAME;
		
		private string _COLUMN_NAME;
		
		private System.Nullable<int> _ORDINAL_POSITION;
		
		private string _COLUMN_DEFAULT;
		
		private string _IS_NULLABLE;
		
		private string _DATA_TYPE;
		
		private System.Nullable<int> _CHARACTER_MAXIMUM_LENGTH;
		
		private System.Nullable<int> _CHARACTER_OCTET_LENGTH;
		
		private System.Nullable<byte> _NUMERIC_PRECISION;
		
		private System.Nullable<short> _NUMERIC_PRECISION_RADIX;
		
		private System.Nullable<int> _NUMERIC_SCALE;
		
		private System.Nullable<short> _DATETIME_PRECISION;
		
		private string _CHARACTER_SET_CATALOG;
		
		private string _CHARACTER_SET_SCHEMA;
		
		private string _CHARACTER_SET_NAME;
		
		private string _COLLATION_CATALOG;
		
		private string _COLLATION_SCHEMA;
		
		private string _COLLATION_NAME;
		
		private string _DOMAIN_CATALOG;
		
		private string _DOMAIN_SCHEMA;
		
		private string _DOMAIN_NAME;
		
		public COLUMN()
		{
		}
		
		[Column(Storage="_TABLE_CATALOG", DbType="NVarChar(128)")]
		public string TABLE_CATALOG
		{
			get
			{
				return this._TABLE_CATALOG;
			}
			set
			{
				if ((this._TABLE_CATALOG != value))
				{
					this._TABLE_CATALOG = value;
				}
			}
		}
		
		[Column(Storage="_TABLE_SCHEMA", DbType="NVarChar(128)")]
		public string TABLE_SCHEMA
		{
			get
			{
				return this._TABLE_SCHEMA;
			}
			set
			{
				if ((this._TABLE_SCHEMA != value))
				{
					this._TABLE_SCHEMA = value;
				}
			}
		}
		
		[Column(Storage="_TABLE_NAME", DbType="NVarChar(128) NOT NULL", CanBeNull=false)]
		public string TABLE_NAME
		{
			get
			{
				return this._TABLE_NAME;
			}
			set
			{
				if ((this._TABLE_NAME != value))
				{
					this._TABLE_NAME = value;
				}
			}
		}
		
		[Column(Storage="_COLUMN_NAME", DbType="NVarChar(128)")]
		public string COLUMN_NAME
		{
			get
			{
				return this._COLUMN_NAME;
			}
			set
			{
				if ((this._COLUMN_NAME != value))
				{
					this._COLUMN_NAME = value;
				}
			}
		}
		
		[Column(Storage="_ORDINAL_POSITION", DbType="Int")]
		public System.Nullable<int> ORDINAL_POSITION
		{
			get
			{
				return this._ORDINAL_POSITION;
			}
			set
			{
				if ((this._ORDINAL_POSITION != value))
				{
					this._ORDINAL_POSITION = value;
				}
			}
		}
		
		[Column(Storage="_COLUMN_DEFAULT", DbType="NVarChar(4000)")]
		public string COLUMN_DEFAULT
		{
			get
			{
				return this._COLUMN_DEFAULT;
			}
			set
			{
				if ((this._COLUMN_DEFAULT != value))
				{
					this._COLUMN_DEFAULT = value;
				}
			}
		}
		
		[Column(Storage="_IS_NULLABLE", DbType="VarChar(3)")]
		public string IS_NULLABLE
		{
			get
			{
				return this._IS_NULLABLE;
			}
			set
			{
				if ((this._IS_NULLABLE != value))
				{
					this._IS_NULLABLE = value;
				}
			}
		}
		
		[Column(Storage="_DATA_TYPE", DbType="NVarChar(128)")]
		public string DATA_TYPE
		{
			get
			{
				return this._DATA_TYPE;
			}
			set
			{
				if ((this._DATA_TYPE != value))
				{
					this._DATA_TYPE = value;
				}
			}
		}
		
		[Column(Storage="_CHARACTER_MAXIMUM_LENGTH", DbType="Int")]
		public System.Nullable<int> CHARACTER_MAXIMUM_LENGTH
		{
			get
			{
				return this._CHARACTER_MAXIMUM_LENGTH;
			}
			set
			{
				if ((this._CHARACTER_MAXIMUM_LENGTH != value))
				{
					this._CHARACTER_MAXIMUM_LENGTH = value;
				}
			}
		}
		
		[Column(Storage="_CHARACTER_OCTET_LENGTH", DbType="Int")]
		public System.Nullable<int> CHARACTER_OCTET_LENGTH
		{
			get
			{
				return this._CHARACTER_OCTET_LENGTH;
			}
			set
			{
				if ((this._CHARACTER_OCTET_LENGTH != value))
				{
					this._CHARACTER_OCTET_LENGTH = value;
				}
			}
		}
		
		[Column(Storage="_NUMERIC_PRECISION", DbType="TinyInt")]
		public System.Nullable<byte> NUMERIC_PRECISION
		{
			get
			{
				return this._NUMERIC_PRECISION;
			}
			set
			{
				if ((this._NUMERIC_PRECISION != value))
				{
					this._NUMERIC_PRECISION = value;
				}
			}
		}
		
		[Column(Storage="_NUMERIC_PRECISION_RADIX", DbType="SmallInt")]
		public System.Nullable<short> NUMERIC_PRECISION_RADIX
		{
			get
			{
				return this._NUMERIC_PRECISION_RADIX;
			}
			set
			{
				if ((this._NUMERIC_PRECISION_RADIX != value))
				{
					this._NUMERIC_PRECISION_RADIX = value;
				}
			}
		}
		
		[Column(Storage="_NUMERIC_SCALE", DbType="Int")]
		public System.Nullable<int> NUMERIC_SCALE
		{
			get
			{
				return this._NUMERIC_SCALE;
			}
			set
			{
				if ((this._NUMERIC_SCALE != value))
				{
					this._NUMERIC_SCALE = value;
				}
			}
		}
		
		[Column(Storage="_DATETIME_PRECISION", DbType="SmallInt")]
		public System.Nullable<short> DATETIME_PRECISION
		{
			get
			{
				return this._DATETIME_PRECISION;
			}
			set
			{
				if ((this._DATETIME_PRECISION != value))
				{
					this._DATETIME_PRECISION = value;
				}
			}
		}
		
		[Column(Storage="_CHARACTER_SET_CATALOG", DbType="NVarChar(128)")]
		public string CHARACTER_SET_CATALOG
		{
			get
			{
				return this._CHARACTER_SET_CATALOG;
			}
			set
			{
				if ((this._CHARACTER_SET_CATALOG != value))
				{
					this._CHARACTER_SET_CATALOG = value;
				}
			}
		}
		
		[Column(Storage="_CHARACTER_SET_SCHEMA", DbType="NVarChar(128)")]
		public string CHARACTER_SET_SCHEMA
		{
			get
			{
				return this._CHARACTER_SET_SCHEMA;
			}
			set
			{
				if ((this._CHARACTER_SET_SCHEMA != value))
				{
					this._CHARACTER_SET_SCHEMA = value;
				}
			}
		}
		
		[Column(Storage="_CHARACTER_SET_NAME", DbType="NVarChar(128)")]
		public string CHARACTER_SET_NAME
		{
			get
			{
				return this._CHARACTER_SET_NAME;
			}
			set
			{
				if ((this._CHARACTER_SET_NAME != value))
				{
					this._CHARACTER_SET_NAME = value;
				}
			}
		}
		
		[Column(Storage="_COLLATION_CATALOG", DbType="NVarChar(128)")]
		public string COLLATION_CATALOG
		{
			get
			{
				return this._COLLATION_CATALOG;
			}
			set
			{
				if ((this._COLLATION_CATALOG != value))
				{
					this._COLLATION_CATALOG = value;
				}
			}
		}
		
		[Column(Storage="_COLLATION_SCHEMA", DbType="NVarChar(128)")]
		public string COLLATION_SCHEMA
		{
			get
			{
				return this._COLLATION_SCHEMA;
			}
			set
			{
				if ((this._COLLATION_SCHEMA != value))
				{
					this._COLLATION_SCHEMA = value;
				}
			}
		}
		
		[Column(Storage="_COLLATION_NAME", DbType="NVarChar(128)")]
		public string COLLATION_NAME
		{
			get
			{
				return this._COLLATION_NAME;
			}
			set
			{
				if ((this._COLLATION_NAME != value))
				{
					this._COLLATION_NAME = value;
				}
			}
		}
		
		[Column(Storage="_DOMAIN_CATALOG", DbType="NVarChar(128)")]
		public string DOMAIN_CATALOG
		{
			get
			{
				return this._DOMAIN_CATALOG;
			}
			set
			{
				if ((this._DOMAIN_CATALOG != value))
				{
					this._DOMAIN_CATALOG = value;
				}
			}
		}
		
		[Column(Storage="_DOMAIN_SCHEMA", DbType="NVarChar(128)")]
		public string DOMAIN_SCHEMA
		{
			get
			{
				return this._DOMAIN_SCHEMA;
			}
			set
			{
				if ((this._DOMAIN_SCHEMA != value))
				{
					this._DOMAIN_SCHEMA = value;
				}
			}
		}
		
		[Column(Storage="_DOMAIN_NAME", DbType="NVarChar(128)")]
		public string DOMAIN_NAME
		{
			get
			{
				return this._DOMAIN_NAME;
			}
			set
			{
				if ((this._DOMAIN_NAME != value))
				{
					this._DOMAIN_NAME = value;
				}
			}
		}
	}
	
	[Table(Name="INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE")]
	public partial class CONSTRAINT_COLUMN_USAGE
	{
		
		private string _TABLE_CATALOG;
		
		private string _TABLE_SCHEMA;
		
		private string _TABLE_NAME;
		
		private string _COLUMN_NAME;
		
		private string _CONSTRAINT_CATALOG;
		
		private string _CONSTRAINT_SCHEMA;
		
		private string _CONSTRAINT_NAME;
		
		public CONSTRAINT_COLUMN_USAGE()
		{
		}
		
		[Column(Storage="_TABLE_CATALOG", DbType="NVarChar(128)")]
		public string TABLE_CATALOG
		{
			get
			{
				return this._TABLE_CATALOG;
			}
			set
			{
				if ((this._TABLE_CATALOG != value))
				{
					this._TABLE_CATALOG = value;
				}
			}
		}
		
		[Column(Storage="_TABLE_SCHEMA", DbType="NVarChar(128)")]
		public string TABLE_SCHEMA
		{
			get
			{
				return this._TABLE_SCHEMA;
			}
			set
			{
				if ((this._TABLE_SCHEMA != value))
				{
					this._TABLE_SCHEMA = value;
				}
			}
		}
		
		[Column(Storage="_TABLE_NAME", DbType="NVarChar(128) NOT NULL", CanBeNull=false)]
		public string TABLE_NAME
		{
			get
			{
				return this._TABLE_NAME;
			}
			set
			{
				if ((this._TABLE_NAME != value))
				{
					this._TABLE_NAME = value;
				}
			}
		}
		
		[Column(Storage="_COLUMN_NAME", DbType="NVarChar(128)")]
		public string COLUMN_NAME
		{
			get
			{
				return this._COLUMN_NAME;
			}
			set
			{
				if ((this._COLUMN_NAME != value))
				{
					this._COLUMN_NAME = value;
				}
			}
		}
		
		[Column(Storage="_CONSTRAINT_CATALOG", DbType="NVarChar(128)")]
		public string CONSTRAINT_CATALOG
		{
			get
			{
				return this._CONSTRAINT_CATALOG;
			}
			set
			{
				if ((this._CONSTRAINT_CATALOG != value))
				{
					this._CONSTRAINT_CATALOG = value;
				}
			}
		}
		
		[Column(Storage="_CONSTRAINT_SCHEMA", DbType="NVarChar(128)")]
		public string CONSTRAINT_SCHEMA
		{
			get
			{
				return this._CONSTRAINT_SCHEMA;
			}
			set
			{
				if ((this._CONSTRAINT_SCHEMA != value))
				{
					this._CONSTRAINT_SCHEMA = value;
				}
			}
		}
		
		[Column(Storage="_CONSTRAINT_NAME", DbType="NVarChar(128) NOT NULL", CanBeNull=false)]
		public string CONSTRAINT_NAME
		{
			get
			{
				return this._CONSTRAINT_NAME;
			}
			set
			{
				if ((this._CONSTRAINT_NAME != value))
				{
					this._CONSTRAINT_NAME = value;
				}
			}
		}
	}
	
	[Table(Name="INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS")]
	public partial class REFERENTIAL_CONSTRAINT
	{
		
		private string _CONSTRAINT_CATALOG;
		
		private string _CONSTRAINT_SCHEMA;
		
		private string _CONSTRAINT_NAME;
		
		private string _UNIQUE_CONSTRAINT_CATALOG;
		
		private string _UNIQUE_CONSTRAINT_SCHEMA;
		
		private string _UNIQUE_CONSTRAINT_NAME;
		
		private string _MATCH_OPTION;
		
		private string _UPDATE_RULE;
		
		private string _DELETE_RULE;
		
		public REFERENTIAL_CONSTRAINT()
		{
		}
		
		[Column(Storage="_CONSTRAINT_CATALOG", DbType="NVarChar(128)")]
		public string CONSTRAINT_CATALOG
		{
			get
			{
				return this._CONSTRAINT_CATALOG;
			}
			set
			{
				if ((this._CONSTRAINT_CATALOG != value))
				{
					this._CONSTRAINT_CATALOG = value;
				}
			}
		}
		
		[Column(Storage="_CONSTRAINT_SCHEMA", DbType="NVarChar(128)")]
		public string CONSTRAINT_SCHEMA
		{
			get
			{
				return this._CONSTRAINT_SCHEMA;
			}
			set
			{
				if ((this._CONSTRAINT_SCHEMA != value))
				{
					this._CONSTRAINT_SCHEMA = value;
				}
			}
		}
		
		[Column(Storage="_CONSTRAINT_NAME", DbType="NVarChar(128) NOT NULL", CanBeNull=false)]
		public string CONSTRAINT_NAME
		{
			get
			{
				return this._CONSTRAINT_NAME;
			}
			set
			{
				if ((this._CONSTRAINT_NAME != value))
				{
					this._CONSTRAINT_NAME = value;
				}
			}
		}
		
		[Column(Storage="_UNIQUE_CONSTRAINT_CATALOG", DbType="NVarChar(128)")]
		public string UNIQUE_CONSTRAINT_CATALOG
		{
			get
			{
				return this._UNIQUE_CONSTRAINT_CATALOG;
			}
			set
			{
				if ((this._UNIQUE_CONSTRAINT_CATALOG != value))
				{
					this._UNIQUE_CONSTRAINT_CATALOG = value;
				}
			}
		}
		
		[Column(Storage="_UNIQUE_CONSTRAINT_SCHEMA", DbType="NVarChar(128)")]
		public string UNIQUE_CONSTRAINT_SCHEMA
		{
			get
			{
				return this._UNIQUE_CONSTRAINT_SCHEMA;
			}
			set
			{
				if ((this._UNIQUE_CONSTRAINT_SCHEMA != value))
				{
					this._UNIQUE_CONSTRAINT_SCHEMA = value;
				}
			}
		}
		
		[Column(Storage="_UNIQUE_CONSTRAINT_NAME", DbType="NVarChar(128)")]
		public string UNIQUE_CONSTRAINT_NAME
		{
			get
			{
				return this._UNIQUE_CONSTRAINT_NAME;
			}
			set
			{
				if ((this._UNIQUE_CONSTRAINT_NAME != value))
				{
					this._UNIQUE_CONSTRAINT_NAME = value;
				}
			}
		}
		
		[Column(Storage="_MATCH_OPTION", DbType="VarChar(7)")]
		public string MATCH_OPTION
		{
			get
			{
				return this._MATCH_OPTION;
			}
			set
			{
				if ((this._MATCH_OPTION != value))
				{
					this._MATCH_OPTION = value;
				}
			}
		}
		
		[Column(Storage="_UPDATE_RULE", DbType="VarChar(11)")]
		public string UPDATE_RULE
		{
			get
			{
				return this._UPDATE_RULE;
			}
			set
			{
				if ((this._UPDATE_RULE != value))
				{
					this._UPDATE_RULE = value;
				}
			}
		}
		
		[Column(Storage="_DELETE_RULE", DbType="VarChar(11)")]
		public string DELETE_RULE
		{
			get
			{
				return this._DELETE_RULE;
			}
			set
			{
				if ((this._DELETE_RULE != value))
				{
					this._DELETE_RULE = value;
				}
			}
		}
	}
	
	[Table(Name="INFORMATION_SCHEMA.VIEWS")]
	public partial class VIEW
	{
		
		private string _TABLE_CATALOG;
		
		private string _TABLE_SCHEMA;
		
		private string _TABLE_NAME;
		
		private string _VIEW_DEFINITION;
		
		private string _CHECK_OPTION;
		
		private string _IS_UPDATABLE;
		
		public VIEW()
		{
		}
		
		[Column(Storage="_TABLE_CATALOG", DbType="NVarChar(128)")]
		public string TABLE_CATALOG
		{
			get
			{
				return this._TABLE_CATALOG;
			}
			set
			{
				if ((this._TABLE_CATALOG != value))
				{
					this._TABLE_CATALOG = value;
				}
			}
		}
		
		[Column(Storage="_TABLE_SCHEMA", DbType="NVarChar(128)")]
		public string TABLE_SCHEMA
		{
			get
			{
				return this._TABLE_SCHEMA;
			}
			set
			{
				if ((this._TABLE_SCHEMA != value))
				{
					this._TABLE_SCHEMA = value;
				}
			}
		}
		
		[Column(Storage="_TABLE_NAME", DbType="NVarChar(128) NOT NULL", CanBeNull=false)]
		public string TABLE_NAME
		{
			get
			{
				return this._TABLE_NAME;
			}
			set
			{
				if ((this._TABLE_NAME != value))
				{
					this._TABLE_NAME = value;
				}
			}
		}
		
		[Column(Storage="_VIEW_DEFINITION", DbType="NVarChar(4000)")]
		public string VIEW_DEFINITION
		{
			get
			{
				return this._VIEW_DEFINITION;
			}
			set
			{
				if ((this._VIEW_DEFINITION != value))
				{
					this._VIEW_DEFINITION = value;
				}
			}
		}
		
		[Column(Storage="_CHECK_OPTION", DbType="VarChar(7)")]
		public string CHECK_OPTION
		{
			get
			{
				return this._CHECK_OPTION;
			}
			set
			{
				if ((this._CHECK_OPTION != value))
				{
					this._CHECK_OPTION = value;
				}
			}
		}
		
		[Column(Storage="_IS_UPDATABLE", DbType="VarChar(2) NOT NULL", CanBeNull=false)]
		public string IS_UPDATABLE
		{
			get
			{
				return this._IS_UPDATABLE;
			}
			set
			{
				if ((this._IS_UPDATABLE != value))
				{
					this._IS_UPDATABLE = value;
				}
			}
		}
	}
	
	[Table(Name="INFORMATION_SCHEMA.TABLES")]
	public partial class TABLE
	{
		
		private string _TABLE_CATALOG;
		
		private string _TABLE_SCHEMA;
		
		private string _TABLE_NAME;
		
		private string _TABLE_TYPE;
		
		public TABLE()
		{
		}
		
		[Column(Storage="_TABLE_CATALOG", DbType="NVarChar(128)")]
		public string TABLE_CATALOG
		{
			get
			{
				return this._TABLE_CATALOG;
			}
			set
			{
				if ((this._TABLE_CATALOG != value))
				{
					this._TABLE_CATALOG = value;
				}
			}
		}
		
		[Column(Storage="_TABLE_SCHEMA", DbType="NVarChar(128)")]
		public string TABLE_SCHEMA
		{
			get
			{
				return this._TABLE_SCHEMA;
			}
			set
			{
				if ((this._TABLE_SCHEMA != value))
				{
					this._TABLE_SCHEMA = value;
				}
			}
		}
		
		[Column(Storage="_TABLE_NAME", DbType="NVarChar(128) NOT NULL", CanBeNull=false)]
		public string TABLE_NAME
		{
			get
			{
				return this._TABLE_NAME;
			}
			set
			{
				if ((this._TABLE_NAME != value))
				{
					this._TABLE_NAME = value;
				}
			}
		}
		
		[Column(Storage="_TABLE_TYPE", DbType="VarChar(10)")]
		public string TABLE_TYPE
		{
			get
			{
				return this._TABLE_TYPE;
			}
			set
			{
				if ((this._TABLE_TYPE != value))
				{
					this._TABLE_TYPE = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
